FROM python:3.11-slim

WORKDIR /app

# Install FFmpeg + necessary system libs
RUN apt-get update && \
    apt-get install -y ffmpeg libsm6 libxext6 libxrender1 && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy ONLY the worker folder
COPY worker/ ./worker/

# Expose port
EXPOSE 8001

# Start worker service
CMD ["uvicorn", "worker.processor:app", "--host", "0.0.0.0", "--port", "8001"]
